# docker-compose.yml

version: '3.8'

services:
  scrapy:
    build: .
    stdin_open: true
    tty: true
    entrypoint: [ "/usr/bin/fish" ]
    command: echo ""
    environment:
      - SHELL=/usr/bin/fish
    env_file: .env
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8008:8000
    env_file: .env
