[tool.poetry]
name = "planitor"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Reynir = "^2.1.0"
fastapi = "^0.52.0"
jinja2 = "^2.11.1"
sqlalchemy = "^1.3.15"
psycopg2 = "^2.8.4"
uvicorn = "^0.11.3"
requests = "^2.23.0"
aiofiles = "^0.4.0"
hashids = "^1.2.0"
sqlakeyset = "^0.1.1579837191"
pyjwt = "^1.7.1"
sqlalchemy_utils = "^0.36.3"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
email-validator = "^1.0.5"
emails = "^0.5.15"
sentry-sdk = "^0.14.3"
python-multipart = "^0.0.5"
gino = {version = "^1.0rc4", extras = ["starlette"], allow-prereleases = true}

[tool.poetry.dev-dependencies]
ipython = "^7.13.0"
black = "^19.10b0"
ipdb = "^0.13.2"
scrapy = "^2.0.1"
pytest = "^5.4.1"
flake8 = "^3.7.9"
beautifulsoup4 = "^4.8.2"
html5lib = "^1.0.1"
python-dateutil = "^2.8.1"
fold-to-ascii = "^1.0.1"
pytest-ipdb = "^0.1-prerelease2"
rope = "^0.16.0"
migra = "^1.0.1585875302"
httpie = "^2.0.0"
arel = "^0.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
