[tool.poetry]
name = "planitor"
version = "0.1.0"
description = ""
authors = ["Jökull Sólberg <jokull@solberg.is>"]

[tool.poetry.dependencies]
python = "^3.7"
Reynir = "^2.3.1"
jinja2 = "^2.11.1"
sqlalchemy = "^1.3.15"
uvicorn = "^0.11.3"
requests = "^2.24.0"
aiofiles = "^0.5.0"
hashids = "^1.2.0"
sqlakeyset = "^0.1.1579837191"
pyjwt = {extras = ["crypto"], version = "^1.7.1"}
sqlalchemy_utils = "^0.36.3"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
email-validator = "^1.0.5"
emails = "^0.6"
sentry-sdk = "^0.15.1"
python-multipart = "^0.0.5"
fastapi = "^0.58.0"
psycopg2 = "^2.8.5"
redis = "^3.5.3"
dramatiq = "^1.9.0"
iceaddr = "^0.4.0"
tokenizer = "^2.0.6"
sentry-dramatiq = "^0.3.2"
html5lib = "^1.1"
migra = "^1.0.1592301305"

[tool.poetry.dev-dependencies]
ipython = "^7.13.0"
black = "^19.10b0"
ipdb = "^0.13.2"
scrapy = "^2.1.0"
pytest = "^5.4.3"
flake8 = "^3.8.2"
beautifulsoup4 = "^4.9.1"
html5lib = "^1.0.1"
pytest-ipdb = "^0.1-prerelease2"
migra = "^1.0.1585875302"
arel = "^0.1.0"
bpython = "^0.19"
typer = "^0.2.1"

[tool.poetry.scripts]
dev-server = "scripts.development:main"
migrate = "scripts.migrate:sync"
debug = "scripts.shell:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
