import datetime

obj = {
    "url": "https://reykjavik.is/fundargerdir/fundur-nr-80",
    "name": "80",
    "start": datetime.date(2020, 9, 2),
    "description": "Ár 2020, miðvikudaginn 2. september kl. 09:05, var haldinn 80. fundur skipulags- og samgönguráðs Reykjavíkur. Fundurinn var haldinn að Borgartúni 12 - 14, 7. hæð Ráðssal. Viðstödd voru: Sigurborg Ósk Haraldsdóttir, Sara Björg Sigurðardóttir og Kolbrún Baldursdóttir. Eftirtaldir fulltrúar tóku sæti á fundinum með fjarfundabúnaði með vísan til heimilda í auglýsingu nr. 230/2020 um ákvörðun samgöngu- og sveitarstjórnarráðherra skv. VI. bráðabirgðarákvæði sveitarstjórnarlaga, nr. 138/2011:  Pawel Bartoszek, Hjálmar Sveinsson, Valgerður Sigurðardóttir, Hildur Björnsdóttir, Katrín Atladóttir og áheyrnarfulltrúarnir Vigdís Hauksdóttir og Daníel Örn Arnarsson. Eftirtaldir embættismenn sátu fundinn: Ólöf Örvarsdóttir, Björn Axelsson, Þorsteinn Rúnar Hermannsson og Gréta Mar Jósepsdóttir.\nFundarritari var Glóey Helgudóttir Finnsdóttir.\n",
    "minutes": [
        {
            "headline": "Kosning í skipulags- og samgönguráð (USK2018060045),",
            "inquiry": "Lagt fram bréf borgarstjóra, dags. 20. ágúst 2020, þar sem tilkynnt er að Ragna Sigurðardóttir taki sæti í skipulags- og samgönguráði í stað Kristínar Soffíu Jónsdóttur.",
            "serial": "1. fundarliður",
            "case_serial": "US200285",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": "E",
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/kosning_i_skipulags-_og_samgongurad_1.pdf",
                    "length": "49762",
                    "label": "Kosning í skipulags- og samgönguráð",
                }
            ],
        },
        {
            "headline": "Fyrsti áfangi borgarlínu, Ártúnsholt - Hamraborg,",
            "inquiry": "Lögð fram umsögn umhverfis- og skipulagssviðs, Skrifstofu umhverfisgæða, um tillögu að matsáætlun fyrsta áfanga Borgarlínu, Ártúnsholt - Hamraborg, dags. 25. ágúst 2020.",
            "serial": "2. fundarliður",
            "case_serial": "US200299",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Áheyrnarfulltrúi Miðflokksins leggur fram svohljóðandi bókun:",
                    "Hér er á ferðinni umsögn um tillögu að matsáætlun fyrsta áfanga Borgarlínu, Ártúnsholt – Hamraborg, frá Reykjavíkurborg til Skipulagsstofnunar. Margt er þar sem vekur athygli en þó eru nokkur atriði mjög afhjúpandi svo ekki sé meira sagt. Umsögnin afhjúpar að verkefnið er komið mjög stutt hugmyndafræðilega hvað varðar tæknihlið borgarlínu. Í kaflanum um hljóðvist segir: „Hér vantar eina breytu sem er ekki þekkt á þessari stundu sem er hávaði frá væntanlegum ökutækjum Borgarlínunnar. Mat á áhrifum ætti að draga fram mögulega valkosti t.d. hljóðláta rafmagnsvagna og eða vagna með háværari vélar.“ Jafnframt segir í kaflanum um loftgæði: „Líkt og með hljóðvist ætti að reyna að leggja mat á hvers eðli ökutæki Borgarlínunnar verða með tilliti til áhrifa á loftgæði, bæði útblástur og svifryk.“ Er þetta eitthvert grín. Til stendur að leggja í fleiri tugi milljarða ef ekki hundraða í borgarlínu, breyta öllu skipulagi með þrengingarstefnu og rústa aðgengi fjölskyldubílsins að götum borgarinnar og enn er ekki farið að ræða hvort borgarlínuvagnar verði rafmagnsvagnar, eða háværir, mengandi dísel/bensín vagnar. Er ekki tímabært að ríkisstjórnin og nágrannasveitarfélög Reykjavíkur vakni og átti sig á hvaða flopp þetta verkefni er sem keyrt er áfram af borgarstjóra. Það er ekki verkefni þessara aðila að uppfylla kosningaloforð Samfylkingarinnar.",
                ],
                [
                    "Fulltrúar Samfylkingarinnar, Viðreisnar og Pírata leggja fram svohljóðandi gagnbókun:",
                    "Það hefur komið skýrt fram að Borgarlínan verði drifin áfram með vistvænum innlendum orkugjafa. Niðurstöður starfshóps um val á orkugjafa er að vænta innan skamms.",
                ],
                [
                    "Áheyrnarfulltrúi Miðflokksins leggur fram svohljóðandi gagnbókun:",
                    "Borgarlínuverkefnið er martröð aftan úr grárri forneskju. Illa skipulagt, illa framkvæmanlegt og engar áætlanir eru til um stofnkostnað – hvað þá rekstrarkostnað. Allt er í þoku og óvissu. Nútíminn og framtíðin eru vistvænir fjölskyldubílar, aukin hjólreiðanotkun, deilibílar og sjálfkeyrandi ökutæki. Ekkert er fast í hendi í borgarlínuverkefninu nema það að búið er að skipa „borgarlínuhóp“ sem heldur uppi stöðugum áróðri fyrir verkefninu og krafan um að ríkið komi með gríðarlegt fjármagn inn í verkefnið. Ég ítreka á ný – hvers vegna er ríkisstjórnin og nágrannasveitarfélög Reykjavíkur að vinna að því að uppfylla kosningarloforð Dags. B. Eggertssonar, Samfylkingarinnar og meirihlutans í Reykjavík?",
                ],
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    "Umsögn um tillögu að matsáætlun fyrsta áfanga Borgarlínu, Ártúnsholt - Hamraborg. Það virðist vera óvissa um samgöngur til og frá borgarlínu og er hér átt við tengsl við aðrar samgönguleiðir og hverjar þær eiga helst að vera. Hver verður fjöldi bílastæða við borgarlínu? Búast má við að margir munu koma akandi að borgarlínu og geyma bíl sinn við stöðina yfir daginn. \xa0Það þarf almennt að huga vel að samgönguháttum með tilliti til breytinga sem þarf á öðrum samgönguleiðum en \xa0borgarlínunni. Einnig þarf að koma sem fyrst með áætlun um hvernig orkugjafar eiga að vera. Metanvagnar, rafmagnsvagnar á rafhlöðum eða sítengdir vagnar við rafmagnslínu. Allt slíkt hefur áhrif á hávaða frá borgarlínunni svo og útblástur og svifryk. Þetta eru svona þættir sem margir borgarbúar eru að velta fyrir sér. Það liggur þó fyrir að orkugjafinn á að vera vistvænn, innlendur orkugjafi eftir því sem fram hefur komið hjá skipulagsyfirvöldum. Fulltrúi Flokks fólksins myndi ætla að orkugjafinn verði metan þar sem ofgnótt er til af því á söfnunarstað og verður meira þegar GAJA verður orðin virk. Það væri ánægjulegt ef lagst yrði á eitt um að nýta þennan vistvæna, innlenda orkugjafa sem SORPA, fyrirtæki í eigu Reykvíkinga af stærstum hluta framleiðir. Metan er nú brennt á báli, sóað þar sem ekki hefur tekist að koma því á markað.",
                ],
            ],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/borgarlina_artunsholt-hamraborg_umsogn_usk.pdf",
                    "length": "457054",
                    "label": "Borgarlína_Ártúnsholt-Hamraborg, umsögn",
                }
            ],
        },
        {
            "headline": "Umferðaröryggi við Selvogsgrunn,",
            "inquiry": "Lögð fram beiðni íbúa í Laugardalnum að Selvogsgrunni verði lokað við Brúarveg í tilraunaskyni til tveggja ára.",
            "serial": "3. fundarliður",
            "case_serial": "US200301",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    "Beiðni er lögð fram frá íbúum í Laugardalnum um að Selvogsgrunni verði lokað við Brúarveg. Það er mat fulltrúa Flokks fólksins að þetta sé af hinu góða svo fremi sem gott rými er í götunni. Ef meirihluti íbúa telja mikilvægt að prófa þetta í tilraunaskyni á hiklaust að samþykkja það. Fulltrúi Flokks fólksins styður þess beiðni.",
                ]
            ],
            "remarks": "Vísað til meðferðar umhverfis- og skipulagssviðs, Skrifstofu samgöngustjóra og borgarhönnunar.\xa0",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Álfheimar 23, sérmerkt bílastæði fyrir hreyfihamlaða - USK2020080025",
            "inquiry": "Lögð fram umsókn dags. 11. ágúst 2020 um að skipulags- og samgönguráð samþykki að bílastæði við Álfheima 23 verði merkt fyrir hreyfihamlaðan einstakling.",
            "serial": "4. fundarliður",
            "case_serial": "US200303",
            "case_address": "Álfheimar 23",
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Samþykkt.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/alfheimar_23.pdf",
                    "length": "167197",
                    "label": "Álfheimar 23",
                }
            ],
        },
        {
            "headline": "Vesturbrún 8, umsókn um sérmerkt stæði fyrir hreyfihamlaða - USK2020080024",
            "inquiry": "Lögð fram umsókn dags. 11. ágúst 2020 um að skipulags- og samgönguráð samþykki að bílastæði við Vesturbrún 8 verði merkt fyrir hreyfihamlaðan einstakling.",
            "serial": "5. fundarliður",
            "case_serial": "US200304",
            "case_address": "Vesturbrún 8",
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": "A",
            "responses": [],
            "remarks": "Samþykkt.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/vesturbrun_8.pdf",
                    "length": "168093",
                    "label": "Vesturbrún 8",
                }
            ],
        },
        {
            "headline": "Afgreiðslufundir skipulagsfulltrúa Reykjavíkur, fundargerð",
            "inquiry": "Lögð fram fundargerð embættisafgreiðslufundar skipulagsfulltrúa frá 28. ágúst 2020.",
            "serial": "6. fundarliður",
            "case_serial": "SN010070",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/afgreidslufundur_skipulagsfulltrua_nr._786.pdf",
                    "length": "66793",
                    "label": "Afgreiðslufundur skipulagsfulltrúa nr. 786",
                }
            ],
        },
        {
            "headline": "Kvosin, Landsímareitur, (fsp) breyting á deiliskipulagi",
            "inquiry": "Lögð fram fyrirspurn THG Arkitekta ehf. dags. 13. maí 2020 ásamt greinargerð dags. 13. maí 2020 um breytingu á deiliskipulagi Kvosarinnar, Landsímareits sem felst í að heimilt verði að vera með gististað á 3 og 4 hæð hússins að Thorvaldsensstræti 2, stækka og breyta nýtingu á kjallara hússins að Thorvaldsensstræti 6 ásamt því að breyta jarðhæð í eitt alrými fyrir viðburði og veitingarekstur, vera með gististað eða hótelíbúðir á efri hæðum húsanna að Aðalstræti 7 og Vallarstræti 4 og gera sólstofu fyrir setustofu og bar á 5. hæð á þaksvölum Thorvaldsenstrætis 5. Einnig er lagt fram minnisblað Icelandair Group f.h. Icelandair Hotels og Lindarvatns dags. 17. mars 2020 og bréf Eflu varðandi hljóðeinangrun NASA salar dags. 3. júlí 2020. Einnig er lögð fram umsögn skipulagsfulltrúa dags. 28. ágúst 2020.",
            "serial": "7. fundarliður",
            "case_serial": "SN200297",
            "case_address": None,
            "case_stadgreinir": "(01.140.4)",
            "entities": [
                {
                    "kennitala": "4407032590",
                    "name": "THG Arkitektar ehf.",
                    "address": "Faxafeni 9, 108 Reykjavík",
                }
            ],
            "subcategory": "B",
            "responses": [],
            "remarks": "Umsögn skipulagsfulltrúa dags. 28.08.2020 er samþykkt",
            "entrants_and_leavers": [],
            "participants": "Lilja Grétarsdóttir verkefnastjóri tekur sæti á fundinum undir þessum lið.",
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/kvosin_landsimareitur.pdf",
                    "length": "4783689",
                    "label": "Kvosin, Landsímareitur",
                }
            ],
        },
        {
            "headline": "Afgreiðslufundur byggingarfulltrúa, fundargerð",
            "inquiry": "Fylgiskjal með fundargerð þessari er fundargerð afgreiðslufundar byggingarfulltrúa nr. 1080 frá 25. ágúst 2020.",
            "serial": "8. fundarliður",
            "case_serial": "BN045423",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/afgreidslufundur_byggingarfulltrua_nr._1080_0.pdf",
                    "length": "89781",
                    "label": "Afgreiðslufundur byggingarfulltrúa nr. 1080",
                }
            ],
        },
        {
            "headline": "Skólavörðustígur 31, Viðbygging",
            "inquiry": "Lagt fram erindi þar sem sótt er um leyfi til að byggja viðbyggingu ásamt því að gera inndregnar svalir á eldri hluta í húsi á lóð nr. 31 við Skólavörðustíg. Erindi var grenndarkynnt frá 2. júní 2020 til og með 31. júlí 2020. Eftirtaldir sendu athugasemdir: Guðbjörg Lilja Pétursdóttir dags. 25. júní 2020 og Sverrir Bjarnason dags. 29. júní 2020. \xa0 Erindinu fylgir umsögn Minjastofnunar dags. 5. júní 2018 og afrit af tölvupósti vegna fellingu trjáa dags. 14. júní 2018. Einnig fylgir umsögn skipulagsfulltrúa dags. 28. ágúst 2020.",
            "serial": "9. fundarliður",
            "case_serial": "BN055576",
            "case_address": "Skólavörðustígur 31",
            "case_stadgreinir": "(01.182.238)",
            "entities": [
                {
                    "kennitala": "1104872319",
                    "name": "Leifur Vilberg Orrason",
                    "address": "Skólavörðustígur 31, 101 Reykjavík",
                },
                {
                    "kennitala": "2112603789",
                    "name": "Orri Wilberg",
                    "address": "Skólavörðustígur 31, 101 Reykjavík",
                },
            ],
            "subcategory": "D",
            "responses": [],
            "remarks": "Samþykkt með vísan til umsagnar skipulagsfulltrúa dags. 28. ágúst 2020.Vísað til fullnaðarafgreiðslu byggingarfulltrúa.",
            "entrants_and_leavers": [],
            "participants": "Sólveig Sigurðardóttir verkefnastjóri tekur sæti á fundinum undir þessum lið.",
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/skolavordustigur_31.pdf",
                    "length": "3214749",
                    "label": "Skólavörðustígur 31",
                }
            ],
        },
        {
            "headline": "Umhverfis- og skipulagssvið, 6 mánaða uppgjör 2020",
            "inquiry": "Lögð fram greinargerð 6. mánaða uppgjörs umhverfis- og skipulagssviðs janúar-júní 2020.",
            "serial": "10. fundarliður",
            "case_serial": "US200295",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Kynnt.\xa0",
            "entrants_and_leavers": [],
            "participants": "Hreinn Ólafsson fjármálastjóri umhverfis- og skipulagssviðs tekur sæti á fundinum undir þessum lið.",
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200295_-_umhverfis-_og_skipulagssvid_6_manada_uppgjor_2020_0.pdf",
                    "length": "489805",
                    "label": "US200295 - Umhverfis- og skipulagssvið, 6 mánaða uppgjör 2020",
                }
            ],
        },
        {
            "headline": "Umhverfis- og skipulagssvið, yfirlit yfir ferðakostnað",
            "inquiry": "Lögð fram skýrsla um ferðakostnað á umhverfis- og skipulagssviði fyrir tímabilið apríl - júní 2020.\xa0",
            "serial": "11. fundarliður",
            "case_serial": "US200296",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": "Hreinn Ólafsson fjármálastjóri umhverfis- og skipulagssviðs tekur sæti á fundinum undir þessum lið.",
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200296_-_umhverfis-_og_skipulagssvid_yfirlit_yfir_ferdakostnad.pdf",
                    "length": "485111",
                    "label": "US200296 - Umhverfis- og skipulagssvið, yfirlit yfir ferðakostnað",
                }
            ],
        },
        {
            "headline": "Umhverfis- og skipulagssvið, yfirlit yfir innkaup yfir 1 m.kr.",
            "inquiry": "Lagðar fram innkaupaskýrslur frá janúar - júní 2020 fyrir aðalsjóð og eignasjóð á kaupum sem fara yfir milljón.",
            "serial": "12. fundarliður",
            "case_serial": "US200297",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": "Hreinn Ólafsson fjármálastjóri umhverfis- og skipulagssviðs tekur sæti á fundinum undir þessum lið.",
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200297_-_yfirlit_yfir_innkaup_i_adalsjodi.pdf",
                    "length": "489352",
                    "label": "US200297 - Yfirlit yfir innkaup í aðalsjóði",
                },
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200297_-_yfirlit_yfir_innkaup_i_eignasjodi.pdf",
                    "length": "572796",
                    "label": "US200297 - Yfirlit yfir innkaup í eignasjóði",
                },
            ],
        },
        {
            "headline": "Yfirlit yfir verkefni innkaupaskrifstofu fyrir júní og júlí 2020, f.h. umhverfis og skipulagssviðs Reykjavíkur (USK2020020031)",
            "inquiry": "Lögð eru fram yfirlit yfir verkefni innkaupaskrifstofu fyrir hönd umhverfis- og skipulagssviðs Reykjavíkur fyrir júní og júlí 2020.",
            "serial": "13. fundarliður",
            "case_serial": "US200293",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": "Hreinn Ólafsson fjármálastjóri umhverfis- og skipulagssviðs tekur sæti á fundinum undir þessum lið.",
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200293_-_yfirlit_yfir_verkefni_innkaupaskrifstofu_fyrir_juni_2020.pdf",
                    "length": "189936",
                    "label": "US200293 - Yfirlit yfir verkefni innkaupaskrifstofu fyrir júní 2020",
                },
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200293_-_yfirlit_yfir_verkefni_innkaupaskrifstofu_fyrir_juli_2020.pdf",
                    "length": "193021",
                    "label": "US200293 - Yfirlit yfir verkefni innkaupaskrifstofu fyrir júlí 2020",
                },
            ],
        },
        {
            "headline": "Vesturás 19-23, málskot",
            "inquiry": "Lagt fram málskot Guðmundar Júlíusar Ólafssonar dags. 30. júní 2020 vegna neikvæðrar afgreiðslu skipulagsfulltrúa frá 26. júní 2020 um stækkun lóðarinnar nr. 19-23 við Vesturás sem felst í að færa lóðarmörk við enda raðhúsið nr. 19, samkvæmt skissu ódags. Einnig eru lagðar fram ljósmyndir og umsögn skipulagsfulltrúa dags. 26. júní 2020.",
            "serial": "14. fundarliður",
            "case_serial": "SN200429",
            "case_address": "Vesturás 19",
            "case_stadgreinir": "(04.385.6)",
            "entities": [
                {
                    "kennitala": "1707695119",
                    "name": "Guðmundur Júlíus Ólafsson",
                    "address": "Vesturás 19, 110 Reykjavík",
                }
            ],
            "subcategory": None,
            "responses": [],
            "remarks": "Umsögn skipulagsfulltrúa, dags. 26. júní 2020, er samþykkt.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Hagasel 23, kæra 65/2020, umsögn, úrskurður",
            "inquiry": "Lagt fram erindi úrskurðarnefndar umhverfis- og auðlindamála dags. 20. júlí 2020 ásamt kæru dags, 18. júlí 2020 þar sem kærð er samþykkt byggingarfulltrúa frá 24. mars 2020 á umsókn um leyfi til að byggja fjölbýlishús undir búsetuúrræði Velferðarsviðs og Félagsbústaða. Einnig er lögð fram umsögn skrifstofu sviðsstjóra dags. 12. ágúst 2020. Jafnframt er lagður fram úrskurður úrskurðarnefndar umhverfis- og auðlindamála frá 21. ágúst 2020.",
            "serial": "15. fundarliður",
            "case_serial": "SN200489",
            "case_address": "Hagasel",
            "case_stadgreinir": "(04.937)",
            "entities": [
                {
                    "kennitala": "7012110140",
                    "name": "Úrskurðarnefnd umhverfis/auðlin",
                    "address": "Borgartúni 21, 105 Reykjavík",
                }
            ],
            "subcategory": None,
            "responses": [
                [
                    "Áheyrnarfulltrúi Miðflokksins leggur fram svohljóðandi bókun:",
                    "Í annað sinn eru áætlanir Reykjavíkurborgar við byggingu risahúss á útivistarsvæði nágranna Hagasels 23 dæmdar ólöglegar af úrskurðarnefnd umhverfis- og auðlindamála og jafnframt er þetta í annað sinn sem almennir borgarar hafa sigur gagnvart stjórnvaldinu Reykjavíkurborg. Það er mikið fagnaðarefni. Félagsbústaðir eiga það inni hjá Reykjavíkurborg að fundin verði önnur lóð undir starfsemina sem vera á í húsinu. Íbúar hafa marg lýst því yfir að þessi lóð er mikið notuð af íbúum jafnt að sumri sem vetri. Það er með öllu óskiljanlegt að borgin leggi slíka áherslu á að útrýma þessu græna svæði sem er hjartað í hverfinu með rúmlega 600 fermetra byggingu. Ég hvet borgaryfirvöld að falla frá þessum uppbyggingaráformum á þessum stað í stað þess að minnka bygginguna svo hún falli að skipulaginu. Það er borginni ekki sæmandi að vera í stríði við íbúa og þrengingarstefna meirihlutans á ekkert erindi inn í þetta rótgróna hverfi.\xa0",
                ]
            ],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Langholtsvegur 136, kæra 35/2020, umsögn, úrskurður",
            "inquiry": "Lagt fram erindi frá úrskurðarnefnd umhverfis- og auðlindamála dags. 11. maí 2020 ásamt kæru dags. 8. maí 2020 þar sem kærð er útgáfa byggingarleyfis dags. 29. apríl 2020 um byggingu bílskúrs og svala á fasteigninni Langholtsvegur 136. Einnig er lögð fram umsögn skrifstofu sviðsstjóra dags. 26. maí 2020. Jafnframt er lagður fram úrskurður úrskurðarnefndar umhverfis- og auðlindamála frá 21. ágúst 2020. Úrskurðarorð: Hafnað er kröfu kærenda um ógildingu ákvörðunar byggingarfulltrúans í Reykjavík frá 10. september 2019 um að samþykkja leyfi til að byggja bílskúr á lóð nr 136 við Langholtsveg og bæta við svölum og svaladyrum á aðra hæð hússins á lóðinni.",
            "serial": "16. fundarliður",
            "case_serial": "SN200298",
            "case_address": "Langholtsvegur 136",
            "case_stadgreinir": "(01.441)",
            "entities": [
                {
                    "kennitala": "7012110140",
                    "name": "Úrskurðarnefnd umhverfis/auðlin",
                    "address": "Borgartúni 21, 105 Reykjavík",
                }
            ],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Heklureitur - Laugavegur 168 og 170-174, nýtt deiliskipulag",
            "inquiry": "Lagt fram bréf borgarstjóra dags. 20. ágúst 2020 vegna staðfestingar borgarráðs s.d. á synjun skipulags- og samgönguráðs frá 12. ágúst 2020 á breytingu á deiliskipulagi fyrir lóðirnar að Laugavegi 168 og 170-174, Heklureitur.\xa0",
            "serial": "17. fundarliður",
            "case_serial": "SN190730",
            "case_address": None,
            "case_stadgreinir": "(01.242)",
            "entities": [
                {
                    "kennitala": "6001695139",
                    "name": "Hekla hf.",
                    "address": "Pósthólf 5310, 125 Reykjavík",
                },
                {
                    "kennitala": "5609973109",
                    "name": "Yrki arkitektar ehf",
                    "address": "Mýrargötu 26, 101 Reykjavík",
                },
            ],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/heklureitur_-_laugavegur_168_og_170-174_0.pdf",
                    "length": "634547",
                    "label": "Heklureitur - Laugavegur 168 og 170-174",
                }
            ],
        },
        {
            "headline": "Tillaga fulltrúa Sjálfstæðisflokksins, um lagfæringar á gatnamótum Strandvegar og Borgarvegar, umsögn - USK2020020042",
            "inquiry": "Lögð fram tillaga fulltrúa Sjálfstæðisflokksins sem barst skipulags- og samgönguráði og var vísað til umsagnar skrifstofu samgöngustjóra 3. apríl 2019. Einnig er lögð fram umsögn dags. 20. ágúst 2020.",
            "serial": "18. fundarliður",
            "case_serial": "US190112",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Fulltrúar Samfylkingarinnar, Viðreisnar, Pírata og Sjálfstæðisflokksins leggja fram svohljóðandi breytingartillögu:",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us190112_-_tillaga_fulltrua_sjalfstaedisflokksins_um_lagfaeringar_a_gatnamotum_strandvegar_og_borgarvegar.pdf",
                    "length": "267055",
                    "label": "US190112 - Tillaga fulltrúa Sjálfstæðisflokksins um lagfæringar á gatnamótum Strandvegar og Borgarvegar",
                },
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us190112_-_umsogn_um_tillogu_fulltrua_sjalfstaedisflokksins_um_lagfaeringar_a_gatnamotum_strandvegar_og_borgarvegar_0.pdf",
                    "length": "112652",
                    "label": "US190112 - Umsögn um tillögu fulltrúa Sjálfstæðisflokksins um lagfæringar á gatnamótum Strandvegar og Borgarvegar",
                },
            ],
        },
        {
            "headline": "Fyrirspurn áheyrnarfulltrúa Miðflokksins, um innkaup hjá Smith & Norland hf., umsögn - USK2020070024",
            "inquiry": "Lögð fram fyrirspurn áheyrnarfulltrúa Miðflokksins sem barst skipulags- og samgönguráði og var vísað til umsagnar skrifstofu samgöngustjóra og borgarhönnunar 1. júlí 2020. Einnig er lögð fram umsögn dags. 20. ágúst 2020.",
            "serial": "19. fundarliður",
            "case_serial": "US200184",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Áheyrnarfulltrúi Miðflokksins leggur fram svohljóðandi bókun:",
                    "Það er mjög gagnrýnivert að allt sem snýr að ljósastýringarmálum í Reykjavík fari ekki í útboð. Einn aðili virðist fá öll innkaup Reykjavíkurborgar í þeim málaflokki. Það er ávísun á að ekki sé um að ræða besta verð sem hægt væri að fá. Stærsti kostnaðarliður framangreinds yfirlit er vegna uppfærslu á miðlægri stýringu umferðarljósa, samtals 39.357.700 kr. Voru þessi innkaup gerð á þágildandi innkaupareglum borgarinnar. Þegar verið er að úthluta gæðum sem innkaup sveitarfélags sannarlegu eru þá verður að gæta þess að ekki ríki einokun á markaði og að sami aðili fái alltaf öll innkaupin. Minnt er á að Reykjavíkurborg hefur í 5 áratugi skipt við þetta eina fyrirtæki án þess að hleypa öðrum að. Það er mjög óeðlilegt. Hér er jafnframt bent á austur þýskt gæluverkefni sem borgarbúar þurfa að greiða fyrir. Austur þýska gæluverkefnið er endurnýju á ljósakerjum á gönguljósum í miðborginni og kosta hver gatnamót 64.000 án virðisaukaskatts. Í alvöru – hvert er þessi meirihluti kominn?\xa0",
                ]
            ],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200184_-_fyrirspurn_aheyrnarfulltrua_midflokksins_um_innkaup_hja_smith_norland_hf.pdf",
                    "length": "266192",
                    "label": "US200184 - Fyrirspurn áheyrnarfulltrúa Miðflokksins um innkaup hjá Smith & Norland hf",
                },
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200184_-_umsogn_vegna_fyrirspurnar_aheyrnarfulltrua_midflokksins_um_innkaup_hja_smith_norland_hf.pdf",
                    "length": "26829",
                    "label": "US200184 - Umsögn vegna fyrirspurnar áheyrnarfulltrúa Miðflokksins um innkaup hjá Smith & Norland hf",
                },
            ],
        },
        {
            "headline": "Fyrirspurn áheyrnarfulltrúa Miðflokksins úr borgarráði, um forgang strætó, lögreglu og slökkviliðs í umferð, umsögn - USK2020060012",
            "inquiry": "Lögð fram fyrirspurn áheyrnarfulltrúa Miðflokksins sem barst borgarráði 14. maí 2020 og var vísað til \xa0meðferðar skipulags- og samgönguráðs þar sem fyrirspurninni var vísað til umsagnar skrifstofu samgöngustjóra og borgarhönnunar 1 .júlí 2020. Einnig er lögð fram umsögn dags. 20. ágúst 2020.",
            "serial": "20. fundarliður",
            "case_serial": "US200216",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200216_-_fyrirspurn_aheyrnarfulltrua_midflokksins_ur_borgarradi.pdf",
                    "length": "34859",
                    "label": "US200216 - Fyrirspurn áheyrnarfulltrúa Miðflokksins úr borgarráði",
                },
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200216_-umsogn_vegna_fyrirspurnar_aheyrnarfulltrua_midflokksins_ur_borgarradi.pdf",
                    "length": "114871",
                    "label": "US200216 -Umsögn vegna fyrirspurnar áheyrnarfulltrúa Miðflokksins úr borgarráði",
                },
            ],
        },
        {
            "headline": "Fyrirspurn áheyrnarfulltrúa Miðflokksins úr borgarráði, um útboð Reykjavíkurborgar og kæru vegna útboðs Reykjavíkurborgar á stýribúnaði umferðarljósa og framkvæmd ljósastýringar frá 1979, umsögn - USK2019110087",
            "inquiry": "Lögð fram fyrirspurn áheyrnarfulltrúa Miðflokksins sem barst borgarráði 7. maí 2020 og var vísað til meðferðar skipulags- og samgönguráðs þar sem fyrirspurninni \xa0var vísað til skrifstofu samgöngustjóra og borgarhönnunar 1. júlí 2020. Einnig er lögð fram umsögn dags. 20. ágúst.",
            "serial": "21. fundarliður",
            "case_serial": "US200217",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Áheyrnarfulltrúi Miðflokksins leggur fram svohljóðandi bókun:",
                    "Það er allt mjög einkennilegt hvað varðar útboðsmál og viðskipti Reykjavíkur þegar kemur að ljósastýringarmálum. Svo virðist að eitt fyrirtæki sitji að kjötkötlunum og nýjum fyrirtækjum er ekki hleypt að borðinu. Útboð eru ógilt og kærð. Samt keyrir borgin áfram sömu stefnu. Meira að segja er ekki búið að úrskurða í hinu ólöglega útboði þá fer borgin af stað með nýtt útboð sama efnis. Nú þegar hefur Reykjavíkurborg þurft að greiða tæpa milljón vegna ógilda útboðsins til eins aðila og enn á eftir að koma í ljós hversu háar upphæðir borgin þarf að greiða til hins aðilans sem kærði útboðið. Í annað sinn er birt löng runa fyrirtækja sem hafa ekkert með fyrirspurnina að gera og eru þær setta fram til að draga athygli frá fyrirspurninni sem snýr eingöngu að ljósabúnaði- og ljósastýringu og aðkomu eins fyrirtækis að einokuninni sem snýr að viðskiptum í ljósastýringarmálum í Reykjavík frá 1979. Hér er jafnframt bent á austur þýskt gæluverkefni sem borgarbúar þurfa að greiða fyrir. Austur þýska gæluverkefnið er endurnýju á ljósakerjum á gönguljósum í miðborginni og kosta hver gatnamót 64.000 án virðisaukaskatts. Í alvöru – hvert er þessi meirihluti kominn?",
                ]
            ],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200217_-_fyrirspurn_aheyrnarfulltrua_midflokksins_ur_borgarradi_um_utbod_reykjavikurborgar.pdf",
                    "length": "12169",
                    "label": "US200217 - Fyrirspurn áheyrnarfulltrúa Miðflokksins úr borgarráði um útboð Reykjavíkurborgar",
                },
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200217_-_umsogn_vegna_fyrirspurnar_aheyrnarfulltrua_midflokksins_ur_borgarradi_um_utbod_reykjavikurborgar.pdf",
                    "length": "47630",
                    "label": "US200217 - Umsögn vegna fyrirspurnar áheyrnarfulltrúa Miðflokksins úr borgarráði um útboð Reykjavíkurborgar",
                },
            ],
        },
        {
            "headline": "Fyrirspurn áheyrnarfulltrúa Flokks fólksins, umsögn",
            "inquiry": "Lögð er fram fyrirspurn Flokks fólksins um hvað stöðvun á framkvæmdum fráreinar af Bústaðarvegi inn á Kringlumýrarbraut til suðurs hafi kostað borgina. Einnig er lögð fram umsögn skipulagsfulltrúa dags. 28. ágúst 2020.",
            "serial": "22. fundarliður",
            "case_serial": "US200089",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": None,
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [
                {
                    "type": "application/pdf",
                    "url": "https://fundur.reykjavik.is/sites/default/files/agenda-items/us200089_-_umsogn_vegna_fyrirspurnar_aheyrnarfulltrua_flokks_folksins_vardandi_stodvun_a_framkvaemdum.pdf",
                    "length": "182483",
                    "label": "US200089 - Umsögn vegna fyrirspurnar áheyrnarfulltrúa Flokks fólksins varðandi stöðvun á framkvæmdum",
                }
            ],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi tillögur,",
            "inquiry": "Nú er verið að kynna nýtt hverfisskipulag fyrir Breiðholt. Í gangi er viðvera skipulagsyfirvalda sem hefur bæði verið í Mjódd og í Gerðubergi. Fulltrúi Flokks fólksins leggur til að: 1. Viðverudögum verði fjölgað og framhaldið í a.m.k. mánuð í viðbót eða eins lengi og þörf þykir og óskir eru um. 2. Að komið verði upp sérstökum ábendingarhnappi á vefsíðu Reykjavíkur þar sem hægt er að senda inn ábendingar um hverfisskipulagið. 3. Að auglýst verði sérstakt símanúmer sem hægt er að hringja í hafi viðkomandi ábendingu eða athugasemd við hverfisskipulagið. 4. Að beðið verði eftir að COVID aðstæður verði öruggari og þá verði haldnir íbúaráðsfundi í hverju hverfi og fyrir hverfið í heild. Í því COVID ástandi sem nú ríkir treysta sumir sér ekki út úr húsi af ótta við smit. Hér þarf að gæta að jafnræði og sjá til þess að aðstæður séu með þeim hætti að allir hafi jöfn tækifæri til að kynna sér hugmyndirnar og koma skoðunum sínum á framfæri með beinum hætti. 5. Fulltrúi Flokks fólksins leggur til að þeir sem standa vaktina í viðveru vegna hverfisskipulags Breiðholts verði einnig þeir aðilar sem eru höfundar hugmyndinna hvort sem það eru arkitektar eða aðrir skipulagsfrömuðir Reykjavíkur.",
            "serial": "23. fundarliður",
            "case_serial": "US200272",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Fulltrúar Samfylkingarinnar, Viðreisnar og Pírata leggja fram svohljóðandi bókun:",
                    "Mikil þátttaka hefur verið í samráðsferli sem sést bæði á mætingu í Mjódd og Gerðuberg, áhorf á streymisfundi og mætingu í hverfisgöngur. Ekki er talin þörf á að ráðið handstýri því hvaða starfsmaður mæti hvert og hvenær með þeim hætti sem tillagan leggur til.",
                ],
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    "Tillögum Flokks fólksins um að auka aðgengi Breiðhyltinga að skipulagsyfirvöldum vegna hverfisskipulags Breiðholts hefur verið felld. Skipulagsyfirvöld telja ekki þörf á fjölgun viðveru eða frekari fundum þar sem mikil þátttaka hefur verið í samráðsferli.\nFulltrúi Flokks fólksins lagði til að viðverudögum verði fjölgað í Mjódd og Gerðubergi vegna COVID ástandsins. Einnig fannst Flokki fólksins mikilvægt að beðið verði eftir að COVID aðstæður verði öruggari svo hægt er að halda almennilega íbúaráðsfundir í hverju hverfi og fyrir hverfið í heild. Í því COVID ástandi sem nú ríkir treysta sumir sér ekki út úr húsi af ótta við smit. Sumir eru einnig í sóttkví og einangrun vegna COVID.\nHér þarf að gæta að jafnræði og sjá til þess að aðstæður séu með þeim hætti að allir hafi jöfn tækifæri til að kynna sér hugmyndirnar og koma skoðunum sínum á framfæri með beinum hætti. \xa0Með því að fella þessa tillögu er verið að loka fyrir þann möguleika að það fólk sem er fast heima vegna COVID geti komið til skrafs og ráðagerðar. Fyrir þá sem eru fastir heima þeim þarf að bjóða aðrar leiðir til að fá kynningu og koma ábendingum sínum á framfæri. Vel má hugsa sér að starfsmaður fari í heimsóknir til fólks sem óska eftir að ræða málin.",
                ],
            ],
            "remarks": "Tillagan er felld með fjórum greiddum atkvæðum fulltrúa Samfylkingarinnar, Viðreisnar og Pírata. Fulltrúar Sjálfstæðisflokksins sitja hjá.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi tillögu, varðandi bílastæðamál",
            "inquiry": "Tillaga Flokks fólksins að skipulagsyfirvöld taki alvarlega ábendingar fólks sem lúta að bílastæðamálum í hinu nýja hverfisskipulagi Breiðholts .Fulltrúi Flokks fólksins hefur orðið var við á m.a. á samfélagsmiðlum að það sem liggur hvað mest á fólki varðandi nýtt hverfisskipulag í Breiðholti er fyrirsjáanlegur skortur á bílastæðum. Flokkur fólksins leggur því til að skipulagsyfirvöld taki alvarlega ábendingar fólks sem lúta að bílastæðamálum í hinu nýja hverfisskipulagi Breiðholts. Víða er nú þegar skortur á bílastæðum. Horfast þarf einnig í augu við þá staðreynt að það rýrir sölugildi eignar ef ekki fylgir bílastæði. Ávallt verður einnig að muna að hreyfihamlaðir aka frekar bíl en hjóla. Sjálfsagt er að þétta byggð upp að vissu marki en þó ekki á kostnað bílastæða eða grænna svæða. Skipulagsyfirvöld ættu að hvetja til aksturs á vistvænum bílum svo sem raf- og metanbílum. Enda þótt \xa0borgarlína sé fyrirhuguð í Mjódd mun það ekki breyta miklu um bílanotkun fólks sem áfram þarf að nota bíl til að koma börnum sínum í leik-, og grunnskóla sem og frístund. Einnig til að komast í vinnu og til að komast í borgarlínu hyggist það nota hana. \xa0Enn liggur ekki fyrir hvernig bílastæðamálum verður háttað í kringum borgarlínustöðina í Mjódd.\xa0",
            "serial": "24. fundarliður",
            "case_serial": "US200273",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Fulltrúar Samfylkingarinnar, Viðreisnar og Pírata leggja fram svohljóðandi bókun:",
                    "Allar tillögur og uppástungur verða teknar til skoðunar og þeim svarað. Hins vegar er ekki rétt að ráðið að taki afstöðu til einstaka hugmynda meðan hverfisskipulagið er enn í vinnslu.",
                ],
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    "Tillaga Flokks fólksins \xa0að skipulagsyfirvöld taki alvarlega ábendingar fólks sem lúta að bílastæðamálum í hinu nýja hverfisskipulagi Breiðholts hefur verið vísað frá. Það er miður. Hér er ekki verið að biðja um að ráðið taki afstöðu til einstakra hugmynda heldur frekar að skipulagsyfirvöld verði enn meðvitaðri um hvar áhyggjur fólks liggja einna helst. Bílatæðamálin liggja þungt á stórum hópi Breiðhyltinga. Nú þegar er skortur á bílastæðum víða í Breiðholti og eftir því sem best er séð þá leiðir þetta nýja hverfisskipulag til enn meiri vandræða í þessum efni. Þetta vita þeir sem staðið hafa vaktina í Gerðubergi og Mjódd. Spurning er hvort skipulagsyfirvöld munu taka á þessum ábendingum mark, gera eitthvað með þær, reyna að virða óskir hverfisbúa?",
                ],
            ],
            "remarks": "Tillögunni er vísað frá með fjórum greiddum atkvæðum fulltrúa Samfylkingarinnar, Viðreisnar og Pírata. Fulltrúar Sjálfstæðisflokksins sitja hjá.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi tillögur, varðandi nýtt hverfisskipulag í Breiðholti",
            "inquiry": "Fulltrúi Flokks fólksins leggur til að eftirfarandi hugmyndir verði skoðaðar í tengslum við nýtt hverfisskipulag í Breiðholti: 1. Að skoða möguleikann á því að fá \xa0fleiri skóla í hverfið t.d. Listaháskólann fluttan í Breiðholtið í stað þess að hrúga öllum háskólum á sama blettinn í Vatnsmýrinni. 2. Að skoða nánar hugmyndir um skrúð- eða lystigarði í efra Breiðholti. 3. Að skoða flutning opinberra stofnana í hverfið.\xa0",
            "serial": "25. fundarliður",
            "case_serial": "US200274",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Fulltrúar Samfylkingarinnar, Viðreisnar og Pírata leggja fram svohljóðandi bókun:",
                    "Hverfisskipulagið er í vinnslu. Það væri óeðlilegt ef ráðið myndi á þessu stigi málsins taka upp nokkrar hugmyndir sem fram hafa komið í samráðsferlinu og hampað sem sínum. Tillögunni er vísað frá.",
                ],
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    "Tillögu Flokks fólksins um að skoðað ákveðnar nýjungar í Breiðholti hefur verið vísað frá. Lagt var til að skoða möguleikann á því að fá \xa0fleiri skóla í hverfið t.d. Listaháskólann fluttan í Breiðholtið í stað þess að hrúga öllum háskólum á sama blettinn í Vatnsmýrinni; að \xa0skoða nánar hugmyndir um skrúð- eða lystigarði í efra Breiðholti og skoða flutning opinberra stofnana í hverfið. Fulltrúi Flokks fólksins er hissa á þessum viðbrögðum skipulagsyfirvalda. Er ekki verið að biðja um ábendingar og tillögur? Síðan þegar fulltrúi Flokks fólksins og íbúi í Breiðholti kemur með þær er þeim hafnað! Hér eru tillögur sem vert er að skoða. Það er sjálfsagt að dreifa bæði skólum og fyrirtækjum um borgina til að létta á álagi á ákveðnum stöðum ekki síst í umferðinni.",
                ],
            ],
            "remarks": "Tillögunni er vísað frá með fjórum greiddum atkvæðum fulltrúa Samfylkingarinnar, Viðreisnar og Pírata. Fulltrúar Sjálfstæðisflokksins sitja hjá.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn, varðandi nýtt hverfisskipulag",
            "inquiry": "Nú er verið að kynna nýtt hverfisskipulag fyrir Breiðholt. Í gangi er viðvera skipulagsyfirvalda sem hefur bæði verið í Mjódd og í Gerðubergi og göngutúrar um hverfið. Fulltrúi Flokks fólksins óskar að fá upplýsingar um aðsókn á viðverufundina og \xa0fjölda þeirra sem fóru í göngutúra um hverfið með skipulagsyfirvöldum. Óskað er einnig upplýsinga um fjölda ábendinga sem hafa borist og að þær verði flokkaðar eftir innihaldi. Loks er spurt um aldursskiptingu þeirra sem komu á viðverufundina og í göngutúrana.",
            "serial": "26. fundarliður",
            "case_serial": "US200275",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umsagnar umhverfis og skipulagssviðs, Skrifstofu skipulagsfulltrúa.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn, um viðhald gatna í Þingholtsstræti og nágrenni",
            "inquiry": "Í gangi hafa verið framkvæmdir í Þingholtsstræti og nágrenni. Fulltrúi Flokks fólksins óskar upplýsinga um verkefnastöðu á málningu gatna/bílastæða í miðbænum t.d. við Þingholtsstræti, og að minnsta kosti hluta Bókhlöðustígs og Skálholtsstígs. Hvenær hófst verkið og hvenær voru áætluð verklok?\xa0\nHver er staða viðhalds, vatnsræsingar og viðgerðar í Þingholtsstrætinu og næsta nágrennis?",
            "serial": "27. fundarliður",
            "case_serial": "US200276",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umsagnar umhverfis - og skipulagssviðs, Skrifstofu framkvæmda og viðhalds.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn, um afgreiðslu erinda hjá skipulagsyfirvöldum borgarinnar",
            "inquiry": "Það hefur nokkuð borið á því að fólk er ekki að ná sambandi við skipulagsyfirvöld Reykjavíkurborg þegar það vill koma áleiðis sem dæmi ábendingum, er með fyrirspurnir eða önnur erindi. Þá hefur borið á því stundum að hver vísar á annan, skeytum ekki svarað fyrr en seint um síðir og enn síður nær fólk í gegn með símtali. Skipulagskerfi borgarinnar er orðið nokkuð stórt bákn og virkar stundum eins og hægri höndin viti ekki hvað sú vinstri gerir. Fulltrúi Flokks fólksins spyr hvort ekki standi til að gera á þessu bragarbót?",
            "serial": "28. fundarliður",
            "case_serial": "US200277",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umsagnar umhverfis- og skipulagssviðs.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi tillögu, varðandi kvartanir",
            "inquiry": 'Í ljósi þess að nokkuð hefur borið á kvörtunum yfir að illa gangi að ná sambandi við skipulagsyfirvöld leggur fulltrúi Flokks fólksins til að starfs- og embættismenn sem og kjörnir fulltrúar meirihlutans í skipulagsráði geri það að vinnureglu sinni að ljúka ekki vinnudegi sínum fyrr en búið er að bregðast \xa0með einum eða öðrum hætti við innkomnum skeytum/skilaboðum sem borist hafa.\xa0\nVissulega gætu komið dagar sem þetta er ekki hægt en í það minnsta muni starfsmenn leitast við að svara samdægurs. Hér er ekki átt við að öll erindi fái fullnaðarafgreiðslur strax enda slíkt ekki raunhæft heldur að þeim sem sent hafa skeyti eða skilaboð verði svarað sem dæmi: "erindið er móttekið/málið er í skoðun/ haft verður samband hið fyrsta", eða eitthvað á þessa leið.\xa0',
            "serial": "29. fundarliður",
            "case_serial": "US200278",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Fulltrúar Samfylkingarinnar, Viðreisnar og Pírata leggja fram svohljóðandi bókun:",
                    "Ekki er hægt að framfylgja þessari tillögu.",
                ],
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    'Tillögu Flokks fólksins um að auka skilvirkni í afgreiðslu erinda frá borgarbúum hefur verið vísað frá. Lagt var til að starfs- og embættismenn sem og kjörnir fulltrúar meirihlutans í skipulagsráði geri það að vinnureglu sinni að ljúka ekki vinnudegi sínum fyrr en búið er að bregðast með einum eða öðrum hætti við innkomnum skeytum/skilaboðum sem borist hafa hefur verið vísað frá. Hér er ekki átt við að öll erindi fái fullnaðarafgreiðslur strax enda slíkt ekki raunhæft heldur að þeim sem sent hafa skeyti eða skilaboð verði svarað sem dæmi: "erindið er móttekið/málið er í skoðun/ haft verður samband hið fyrsta", eða eitthvað á þessa leið. \xa0Fulltrúi Flokks fólksins lagði fram þessa tillögu sökum þess að nokkuð hefur borið á kvörtunum um að illa gangi að ná sambandi við skipulagsyfirvöld. Allt of oft stígur fólk fram og segist ekki ná neinu sambandi við skipulagsyfirvöld. Í meirihlutasáttmála þessarar borgarstjórnar kom skýrt fram að bæta átti þjónustu, auka lýðræði og allt skyldi verða gegnsærra. Hafa þarf sífellt í huga að borgarbúar eiga að koma fyrst. Starfsmenn og kjörnir fulltrúar eru öll í vinnu hjá borgarbúum og eigum að þjónusta hvern og einn sem allra best.',
                ],
            ],
            "remarks": "Tillögunni er vísað frá með fjórum greiddum atkvæðum fulltrúa Samfylkingarinnar, Viðreisnar og Pírata. Fulltrúar Sjálfstæðisflokksins sitja hjá.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi tillögu,",
            "inquiry": "Í ljósi þess að illa gengur oft að komast í samband við starfsmenn og embættismenn borgarinnar leggur fulltrúi Flokks fólksins til að öll netföng og vinnusímar starfs- og embættismanna skipulagssviða borgarinnar séu aðgengileg á netinu. Eins og staðan er nú er borgarbúum boðið upp á að hringja í eitt miðlægt símanúmer til að ná í starfsmenn. Þetta hefur ekki alltaf gengið vel. Leggja þarf áherslu á að borgarbúar hafi greiðan aðgang að embættis- og starfsmönnum allra sviða borgarinnar. Fyrsta skrefið er að hafa netföng og símanúmer sýnileg og aðgengileg.",
            "serial": "30. fundarliður",
            "case_serial": "US200279",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [
                [
                    "Fulltrúar Samfylkingarinnar, Viðreisnar og Pírata leggja fram svohljóðandi bókun:",
                    "Borgarar eiga rétt að hafa samband við stjórnvöld, það eru margar leiðir til að tryggja þann rétt með skilvirkari hætti en þeim að hver og einn geti öllum stundum hringt í hvaða starfsmann borgarinnar sem er. Tillögunni er vísað frá.",
                ],
                [
                    "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi bókun:",
                    "Tillögu Flokks fólksins um að öll netföng og vinnusímar starfs- og embættismanna skipulagssviða borgarinnar séu aðgengileg á netinu hefur verið vísað frá. Telur fulltrúi Flokks fólksins það vera á skjön við það sem lofað var í sáttmála þessa meirihluta en þar er margtalað um aðgengi, að borgarbúar hafi gott aðgengi að borgarkerfinu og embættis- og starfsmönnum. Aðgengi er ekki gott og það er ástæðan fyrir þessari tillögu. Eins og staðan er nú er borgarbúum boðið upp á að hringja í eitt miðlægt símanúmer til að ná í starfsmenn. Þetta hefur ekki alltaf gengið vel. Leggja þarf áherslu á að borgarbúar hafi greiðan aðgang að embættis- og starfsmönnum allra sviða borgarinnar. Fyrsta skrefið er að hafa netföng og símanúmer sýnileg og aðgengileg. Hvað er sjálfsagðra en að hafa upplýsingar um netföng og símanúmer starfsmanna og embættismanna aðgengilegt á netinu? Fulltrúi Flokks fólksins vill að borgarbúar geti sent skeyti og helst hringt beint í viðkomandi starfsmann. Hvorki kjörnir fulltrúar né starfsmenn eiga að vera settir í bómull þegar kemur að aðgengi að þeim.",
                ],
            ],
            "remarks": "Tillögunni er vísað frá með fjórum greiddum atkvæðum fulltrúa Samfylkingarinnar, Viðreisnar og Pírata. Fulltrúar Sjálfstæðisflokksins sitja hjá.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn,",
            "inquiry": "Fulltrúi Flokks fólksins óskar eftir að fá það sundurliðað hvaða hugmyndir sem birtar eru í vinnutillögum nýs hverfisskipulags Breiðholts komu frá íbúum sjálfum og hvaða tillögur komu frá borgar- og skipulagsyfirvöldum eða öðrum?\nVar það t.d. ósk íbúa Breiðholts að svo mikil þétting byggðar yrði?",
            "serial": "31. fundarliður",
            "case_serial": "US200280",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umsagnar umhverfis- og skipulagssviðs, skipulagsfulltrúa.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn,",
            "inquiry": "Fyrirspurnir framhaldi af svari skipulagsyfirvalda við fyrirspurn Flokks fólksins um stæði- og sleppistæði við leik- og grunnskóla. Í svari var vísað í reglur sem skipulag- og samgönguráð samþykkti 19. \xa0desember 2018. Fulltrúi Flokks fólksins spyr hvort reglur um fjölda bíla- og hjólastæða í Reykjavík er fylgt til hins ítrasta. Einnig er spurt hvort það standi til hjá skipulags- og samgönguyfirvöldum að breyta þessum reglum næsta árið í þá átt að fækkað verði enn frekar bílastæðum og sleppistæðum \xa0við einhverja leik-, grunnskóla og frístundarheimili? Stendur það til hjá skipulagsyfirvöldum að setja gjaldskyldu á þau stæði önnur en sleppistæði sem nú eru til staðar fyrir framan leik- og grunnskóla og frístundaheimili?",
            "serial": "32. fundarliður",
            "case_serial": "US200281",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umsagnar umhverfis - og skipulagssviðs, Skrifstofu samgöngustjóra og borgarhönnunar.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn,",
            "inquiry": "Skipulagsyfirvöld leggja til og hafa hafið framkvæmdir á að gera Norðurstíg og Nýlendugötu austan Ægisgötu að vistgötum sem þýðir að bílar eru aftast í forgangi. Hraði hjóla, hjólaskauta eða hjólabretta miðast við gönguhraða. Fulltrúi Flokks fólksins veltir fyrir sér hvaðan þessi hugmynd kemur. Er þetta gert að ósk íbúa og vegfarenda eða er þetta einungis persónulegar ákvarðanir skipulagsfulltrúa? Hvernig var samráði háttað? Hér er enn og aftur spurt um samráð við fólkið í borginni en ekki stafkrókur um slíkt er að finna í framlagningu gagna sem er í formi tilkynningar fremur en tillögu.\xa0",
            "serial": "33. fundarliður",
            "case_serial": "US200282",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umsagnar umhverfis - og skipulagssviðs, Skrifstofu samgöngustjóra og borgarhönnunar.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Flokks fólksins leggur fram svohljóðandi fyrirspurn, varðandi umferð í Ármúla",
            "inquiry": "Þar sem fjöldi verslana og fyrirtækja hefur flutt í Ármúlann undanfarin ár er umferð orðin töluvert mikil um götuna. Umferð hefur aukist vegna t.d. lokana í miðbænum og þrenginga á Grensásveg. Í skipulagslýsingu sem lögð var fram í ágúst 2019 eru fyrirhugaðar breytingar tilgreindar. Í þeim felst að þétta byggð og eiga allt að 450 íbúðir og atvinnuhúsnæði rísi t.d. á lóðinni Suðurlandsbraut 34/Ármúli 31. Fulltrúi Flokks fólksins hefur áhyggjur af því að þarna verði mikil þrengsli þar sem umferð af alls kyns tagi mun aukast ekki síst vegna lokana í miðbænum. Fulltrúi Flokks fólksins óskar eftir upplýsingum um hvaða áhrif breytingar á lóðinni Suðurlandsbraut 34/Ármúli 31 muni hafa á umferð og rými vegfarenda? \xa0Eftir lokun miðbæjarins hefur umferð aukist mjög á þessu svæði, Ármúla og einnig Hallarmúla. Fulltrúa Flokks fólksins hafa einnig borist upplýsingar um að Reykjavíkurborg áformi breytingar á Ármúlanum ofar í götunni, á milli Vegmúla og Selmúla og að hæðarmælingar og annar undirbúningur hafi farið fram. \xa0Fulltrúi Flokks fólksins óskar eftir upplýsingum um hvaða breytingar séu fyrirhugaðar á þessum hluta Ármúla af hálfu skipulagsyfirvalda?",
            "serial": "34. fundarliður",
            "case_serial": "US200305",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Frestað.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
        {
            "headline": "Áheyrnarfulltrúi Miðflokksins leggur fram svohljóðandi fyrirspurn, varðandi rekstraraðila á Laugaveginum",
            "inquiry": "Mikil óvissa er uppi hjá rekstraraðilum í miðbænum og jafnframt þeim sem jafnvel huga að rekstri á þessu svæði hvað varðar lokun fyrir bílaumferð. Þegar ákvörðun var tekin í vor voru ekki gefnar haldbærar upplýsingar um hvað tæki við eftir 1. október og svörin voru mjög loðin.\n1. Hvaða áform eru uppi frá og með 1. október nk. hvað varðar lokun Laugavegarins og annara gatna í miðbænum fyrir bílaumferð?\n2. Hvenær er ákvörðunar að vænta hvort svæðið verði lokað eða opið fyrir bílum?",
            "serial": "35. fundarliður",
            "case_serial": "US200307",
            "case_address": None,
            "case_stadgreinir": None,
            "entities": [],
            "subcategory": None,
            "responses": [],
            "remarks": "Vísað til umhverfis- og skipulagssvið, Skrifstofu samgöngustjóra og borgarhönnunar.",
            "entrants_and_leavers": [],
            "participants": None,
            "attachments": [],
        },
    ],
}
